#!/usr/bin/env python3
"""Select code metadata for one quiz. Reads local files; never writes state."""

import argparse
import ast
import json
import random
import subprocess
import sys
from pathlib import Path

EXTENSIONS = set(".py .pyi .js .jsx .ts .tsx .mjs .cjs .mts .cts .go .rs .java .kt .kts .swift .c .h .cc .cpp .hpp .cs .rb .php .scala .sh .bash .zsh .sql .vue .svelte .ex .exs .erl .hs .lua .r .dart .clj .cljs .fs .fsx .ml .mli .jl .pl .pm .zig .html .css .scss .sass .less .tf .hcl .yaml .yml .toml".split())
EXCLUDED = set(".git .hg .svn .agents .codex .claude .opencode node_modules vendor vendors third_party third-party external dist build out target coverage .next .nuxt .svelte-kit .venv venv env __pycache__ generated __generated__ .cache .turbo .idea .vscode".split())
CATEGORIES = ["concepts", "architecture", "code interpretation", "data flow", "control flow", "edge cases", "error handling", "state changes", "async behavior", "dependencies", "testing", "performance", "security", "configuration", "change impact"]
MAX_BYTES = 512 * 1024


def git(directory, *args):
    result = subprocess.run(["git", "-C", str(directory), *args], capture_output=True, check=False)
    if result.returncode:
        raise ValueError("Open a readable Git repository and run quiz there.")
    return result.stdout


def eligible(root, relative):
    parts = relative.parts
    name = relative.name.lower()
    if relative.is_absolute() or ".." in parts or any(p.lower() in EXCLUDED for p in parts):
        return False
    if relative.suffix.lower() not in EXTENSIONS:
        return False
    if name.endswith((".min.js", ".min.css", ".d.ts", ".g.cs", ".pb.go", ".generated.ts", ".generated.js", "_pb2.py")):
        return False
    if name.endswith(".lock") or "lock." in name or any(s in name for s in ("credential", "secret", ".env")):
        return False
    path = root
    for part in parts:
        path = path / part
        if path.is_symlink():
            return False
    try:
        return path.is_file() and 0 < path.stat().st_size <= MAX_BYTES
    except OSError:
        return False


def inventory(directory):
    root = Path(git(directory, "rev-parse", "--show-toplevel").decode().strip()).resolve()
    names = git(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
    files = sorted({Path(name.decode("utf-8", "surrogateescape")) for name in names.split(b"\0") if name})
    groups = {}
    for relative in files:
        if eligible(root, relative):
            # Equal weight per area, then per file within the selected area.
            area = "/".join(relative.parts[:-1][:2]) or "."
            groups.setdefault(area, []).append(relative)
    return root, groups


def anchor(path, text, rng):
    lines = text.splitlines()
    meaningful = [i for i, line in enumerate(lines, 1) if line.strip() and not line.lstrip().startswith(("#", "//", "/*", "*", "<!--"))]
    if not meaningful or any(len(line) > 2000 for line in lines):
        raise ValueError("Empty, comment-only, or minified source.")
    line = rng.choice(meaningful)
    if path.suffix.lower() == ".py":
        try:
            nodes = [n for n in ast.walk(ast.parse(text)) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
            if nodes:
                line = rng.choice(nodes).lineno
        except (SyntaxError, ValueError, RecursionError):
            pass
    return line, max(1, line - 8), min(len(lines), line + 24)


def sample(directory, rng=None):
    rng = rng or random.SystemRandom()
    root, groups = inventory(directory)
    eligible_count = sum(map(len, groups.values()))
    # Try a few sampled files without reading the entire repository's contents.
    for _ in range(min(20, eligible_count)):
        area = rng.choice(sorted(groups))
        relative = rng.choice(groups[area])
        path = root / relative
        try:
            text = path.read_text(encoding="utf-8")
            if "\0" in text:
                raise ValueError("Binary source.")
            header = "\n".join(text.splitlines()[:8]).lower()
            if any(s in header for s in ("do not edit", "auto-generated", "autogenerated", "@generated")):
                raise ValueError("Generated source.")
            line, start, end = anchor(path, text, rng)
        except (OSError, UnicodeError, ValueError):
            groups[area].remove(relative)
            if not groups[area]:
                del groups[area]
            continue
        categories = CATEGORIES.copy()
        rng.shuffle(categories)
        return {"repository": str(root), "eligible_files": eligible_count, "area": area,
                "file": relative.as_posix(), "anchor_line": line,
                "read_lines": {"start": start, "end": end},
                "category_order": categories, "correct_option": rng.choice("ABCD")}
    raise ValueError("No suitable source found in the sampled files. Choose a repository with readable source code.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="Any directory in the target Git repository")
    args = parser.parse_args()
    try:
        print(json.dumps(sample(args.repo), indent=2))
    except (ValueError, FileNotFoundError) as error:
        message = "Git is required but was not found." if isinstance(error, FileNotFoundError) else str(error)
        print(json.dumps({"error": message}), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
